### ISSUE TITLE
can not input or control when upgrade and a package need configure

### ISSUE THREAD

**Issue by Pancongwen** [FuQiFeiPian/ssh-rpc-agent#5]
## Project version
* tag: 0.0.1
* arch: amd64
## task file 
```json
[
    {
    	"Topic": "update system",
    	"Tasks": [
    		"sudo apt update"
      	]
    },
    {
    	"Topic": "upgrade system",
    	"Tasks": [
    		"sudo apt upgrade -y"
      	]
    },
    {
    	"Topic": "autoremove system",
    	"Tasks": [
    		"sudo apt autoremove -y"
      	]
    }    
] 
```
## Expected behavior
* I can update/upgrade/autoremove successfully

## Actual behavior
the terminal freezes when jump out the configuration of GRUB in upgrade.

**Comment by dorrywhale** [comment]
Please refer to the [issue](https://github.com/FuQiFeiPian/ssh-rpc-agent/issues/4), and see whether it works. It should the same problem.
