### ISSUE TITLE
can not do task when using the ssh key mode which is not in ~/.ssh/know_host

### ISSUE THREAD

**Issue by Pancongwen** [FuQiFeiPian/ssh-rpc-agent#6]
## Project version
* tag: 0.0.1
* arch: amd64

## task file
```json
[
    {
    	"Topic": "show files in HOME",
    	"Tasks": [
    		"ls $HOME"
      	]
    }
]
```

## Expected behavior
* i can `ls` my remote machine's home  

## Actual behavior
```shell
========================================
show files in HOME
========================================

Failed to start &{/usr/bin/sshpass [sshpass -p xxxxx ssh -t -p 22 xxx@xxxxxx /bin/bash -c 'ls $HOME'] []  0xc42000c010 0xc42000c018 0xc42000c020 [] <nil> 0xc4200184e0 exit status 6 <nil> <nil> true [0xc42000c010 0xc42000c018 0xc42000c020] [] [] [] 0xc420060240 <nil>}.
 Error: 
 exit status 6
```

## possible reason
This is the first time i use the ssh key, so the machine is not in the ~/.ssh/know_host.Then i ssh to the remote machine, it prompt me whether to add this machine to the konw_host and i select yes. After those steps, i try the ssh-rpc-agent again, and it works. So i guess this might be the point.

**Comment by dorrywhale** [comment]
Fix it in commit [ac62de63](https://github.com/FuQiFeiPian/ssh-rpc-agent/commit/ac62de63a1ce11959985ec05d48b8b6f187111a3), by add `-o StrictHostKeyChecking=no` for ssh option. It has the side-affect that the entries in `~/.ssh/known_hosts` would not be unique, and the file will grow big along with the time. The admin should take care of the `known_hosts` him/herself.
