### ISSUE TITLE
lost string when using echo

### ISSUE THREAD

**Issue by Pancongwen** [FuQiFeiPian/ssh-rpc-agent#8]
## Project version
* tag: 0.0.1
* arch: amd64

## task file
```json
[
    {
    	"Topic": "It's awsome!",
    	"Tasks": [
    		"echo 'its awsome!' "
      	]
    }
] 
``` 

## Expected behavior
i can echo 'its  awsome'

## Actual behavior
```shell
You have specify 1 tasks on 1 machines
========================================
It's awsome!
========================================

its
Connection to 192.168.21.132 closed.
```

**Comment by dorrywhale** [comment]
Please use the `echo \" it is awsome!\"`. We support escape character "\".

**Comment by Pancongwen** [comment]
ok, thanks!
I try the task with what you suggest and it works.
but escape character `"\"` is not work with `'` .
